package cn.xu.Exception;
/**
 * 测试自定义异常
 * @author shen
 *
 */
public class Test4 {
	
	public static void main(String[] args) {
		Person p=new Person();
		p.setAge(-16);
	}
}


class Person{
	private int age;

	public int getAge() {
		return age;
	}

	public void setAge(int age) throws IllegalAgeException {
		if(age<0) {
			throw new IllegalAgeException("年龄不能为负数");
		}
		this.age = age;
	}
	
}

//还可以改为
//class IllegalAgeException extends Exception
//就是运行时异常了需要抛出
class IllegalAgeException extends Exception{
	public IllegalAgeException() {
		// TODO Auto-generated constructor stub
	}
	
	public IllegalAgeException(String msg) {
		super(msg);
	}
}
